---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: updateapri
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux@example.com
        name: flux
    push:
      branch: flux-erpnext-image-update
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    path: .
    strategy: Setters
