---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: apricot
  namespace: flux-system
spec:
  image: improwised/apricot3
  interval: 5m0s
  secretRef:
    name: docker-secret
