apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: flux-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImEyaDFjMmhoYkcxbGNqcExhSFZ6YUdGc1FERXlNdz09IgoJCX0KCX0KfQ==
