apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: erp-helmrelease
  namespace: erpnext
spec:
  chart:
    spec:
      chart: erpnext
      reconcileStrategy: ChartVersion
      version: 6.0.33
      sourceRef:
        kind: HelmRepository
        name: erp-helm-source
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      pullPolicy: IfNotPresent
      repository: improwised/apricot3 # {"$imagepolicy": "flux-system:apricotpolicy:name"}
      tag: develop-5d605cf-1687252671 # {"$imagepolicy": "flux-system:apricotpolicy:tag"}
    imagePullSecrets:
      - name: regcred
    ingress:
      className: traefik
      enabled: true
      hosts:
        - host: erp.cluster.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      ingressName: erpnext
    nginx:
      resources:
        requests:
          memory: "25Mi"
          cpu: "10m"
    worker:
      gunicorn:
        resources:
          requests:
            memory: "25Mi"
            cpu: "10m"
      default:
        resources:
          requests:
            memory: "25Mi"
            cpu: "10m"
      short:
        resources:
          requests:
            memory: "25Mi"
            cpu: "10m"
      long:
        resources:
          requests:
            memory: "25Mi"
            cpu: "10m"
      scheduler:
        resources:
          requests:
            memory: "25Mi"
            cpu: "10m"
    socketio:
      resources:
        requests:
          memory: "25Mi"
          cpu: "10m"
    jobs:
      createSite:
        adminPassword: changeit
        dbType: mariadb
        enabled: true
        # forceCreate: true
        installApps:
          - erpnext
          - hrms
          - payments
          - india_compliance
          - apricot
        siteName: erp.cluster.local
    persistence:
      worker:
        enabled: true
        size: 8Gi
        storageClass: longhorn
    mariadb:
      global:
        storageClass: longhorn
      auth:
        rootPassword: "bruh"
        username: "erpnext"
        password: "bruh"
