apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: erp-helmrelease
  namespace: erpnext
spec:
  chart:
    spec:
      chart: erpnext
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: erp-helm-source
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      pullPolicy: IfNotPresent
      repository: improwised/apricot3 # {"$imagepolicy": "flux-system:apricotpolicy:name"}
      tag: develop-07e20aa-1684148367 # {"$imagepolicy": "flux-system:apricotpolicy:tag"}
    imagePullSecrets: 
      - regcred
    ingress:
      className: traefik
      enabled: true
      hosts:
      - host: erp.cluster.local
        paths:
        - path: /
          pathType: ImplementationSpecific
      ingressName: erpnext
    jobs:
      createSite:
        adminPassword: changeit
        dbType: mariadb
        enabled: true
        forceCreate: true
        installApps:
        - erpnext
        - hrms
        - payments
        - apricot
        siteName: erp.cluster.local
    persistence:
      worker:
        enabled: true
        size: 8Gi
        storageClass: nfs
