apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: erp-helmrelease
  namespace: erpnext
spec:
  chart:
    spec:
      chart: erpnext
      reconcileStrategy: ChartVersion
      version: 6.0.33
      sourceRef:
        kind: HelmRepository
        name: erp-helm-source
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      pullPolicy: IfNotPresent
      repository: khushalmer/myimg # {"$imagepolicy": "flux-system:apricotpolicy:name"}
      tag: develop-e9f5b00-1683786977 # {"$imagepolicy": "flux-system:apricotpolicy:tag"}
    imagePullSecrets:
      - name: regcred
    ingress:
      className: traefik
      enabled: true
      hosts:
        - host: erp.cluster.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      ingressName: erpnext
    jobs:
      createSite:
        adminPassword: changeit
        dbType: mariadb
        enabled: true
        forceCreate: true
        installApps:
          - erpnext
          - hrms
          - payments
          - india_compliance
          - apricot
        siteName: erp.cluster.local
    persistence:
      worker:
        enabled: true
        size: 8Gi
        storageClass: longhorn
    mariadb:
      global:
        storageClass: longhorn
      auth: 
        rootPassword: "bruh"
        username: "erpnext"
        password: "bruh"
