apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-configmap
  namespace: ttt
  labels:
    app: n8n
    component: configmap
data:
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_DATABASE: "n8n"
  DB_POSTGRESDB_HOST: "postgres"
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_USER: "n8n"
