---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n-database-helmrelease
  namespace: n8n
spec:
  chart:
    spec:
      chart: postgresql
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami-helm-source
        namespace: flux-system
  interval: 10m0s
  values:
    global:
      postgresql:
        auth:
          database: n8n
          existingSecret: "postgres-secrets"
          # postgresPassword: "n8n"
          # username: "n8n"
          # password: "n8n"
      storageClass: longhorn
    nameOverride: postgres
    primary:
      persistence:
        enabled: true
        storageClass: longhorn
