---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n-helmrelease
  namespace: n8n
spec:
  chart:
    spec:
      chart: polymorphic-app
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: n8n-helm-source
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      pullPolicy: IfNotPresent
      repository: n8nio/n8n
      tag: 0.231.0
    services:
    - envFrom:
      - configMapRef:
          name: n8n-configmap
      - secretRef:
          name: n8n-secrets
      healthcheck:
        enabled: false
      ingress:
        enabled: true
        hosts:
        - host: n8n.local
          paths:
          - path: /
            pathType: Prefix
            # serviceName: n8n-helmrelease-n8n-main-svc
            servicePort: 80
      name: n8n-main
      ports:
      - containerPort: 5678
        name: http
        protocol: TCP
      service:
        enabled: true
        ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: 5678
        type: ClusterIP
      # volumeMounts:
      # - mountPath: /home/node/.n8n
      #   name: n8n-volume
      # volumes:
      # - name: n8n-volume
      #   persistentVolumeClaim:
      #   claimName: n8n-storage-claim
