apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-storage-claim
  namespace: n8n
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
